version: '3'
services:
  app:
    container_name: app_server
    build: ./app
    
  nginx:
    container_name: nginx_server
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
